version: '3.6'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: explorer
      POSTGRES_USER: minter
      POSTGRES_PASSWORD: password
    volumes:
      - ./tmp/postgresql:/var/lib/postgresql/data
  centrifugo:
    image: centrifugo/centrifugo
    volumes:
      - ./tmp/centrifugo:/centrifugo
      - ./tmp/var/logs/centrifugo:/var/log/centrifugo
    ports:
      - 8800:8000
