[[constraint]]
  name = "github.com/MinterTeam/minter-explorer-api"
  version = "1.1.4"

[[constraint]]
  name = "github.com/MinterTeam/minter-explorer-tools"
  version = "2.0.2"

[[constraint]]
  name = "github.com/MinterTeam/minter-go-node"
  version = "0.15.0"

[[constraint]]
  name = "github.com/centrifugal/gocent"
  version = "2.0.2"

[[constraint]]
  name = "github.com/MinterTeam/minter-node-go-api"
  version = "1.0.1"

[[constraint]]
  name = "github.com/go-pg/pg"
  version = "^8.0.3"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.9.2"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.4.0"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.3.2"

[prune]
  go-tests = true
  unused-packages = true
