apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
  {{- include "chart.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.env.extenderApiPort }}
      targetPort: {{ .Values.env.extenderApiPort }}
      protocol: TCP
      name: metrics
  selector:
  {{- include "chart.selectorLabels" . | nindent 4 }}
