name: M2

on:
  push:
    branches: [ m2 ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Version
        uses: pCYSl5EDgo/cat@master
        id: version
        with:
          path: VERSION
          trim: true

      - name: Build & Push to Docker Hub
        uses: opspresso/action-docker@master
        env:
          USERNAME: ${{ secrets.MINTER_REGISTRY_USERNAME }}
          PASSWORD: ${{ secrets.MINTER_REGISTRY_PASSWORD }}
          IMAGE_NAME: "explorer-extender"
          REGISTRY: "registry.minter.network"
          DOCKERFILE: ".docker/Dockerfile"
          LATEST: "true"
          VERSION: "${{ steps.version.outputs.text }}"
          TAG_NAME: ${{ github.sha }}
          DOCKER_BUILD_ARGS: --build-arg VERSION=${{ steps.version.outputs.text }}-${{ github.sha::8}}-taconet

      - name: DigitalOcean Kubernetes
        uses: matootie/dokube@master
        with:
          personalAccessToken: ${{ secrets.DIGITALOCEAN_TOKEN }}
          clusterName: k8s-prod-do

      - name: Install helm
        run: wget https://get.helm.sh/helm-v3.3.4-linux-amd64.tar.gz &> /dev/null && tar xvzf helm-v3.3.4-linux-amd64.tar.gz && chmod 777 linux-amd64/helm && ./linux-amd64/helm ls -n taconet

      - name: Deploy to DO
        env:
          TAG_NAME: ${{ github.sha }}
        run: ./linux-amd64/helm upgrade -n taconet -i extender chart/ --atomic --timeout 100s --set image.tag=$TAG_NAME --reuse-values

      - name: notification
        if: cancelled() == false
        uses: xinthink/action-telegram@v1.1
        with:
          botToken: ${{ secrets.TELEGRAM_CI_TOKEN }}
          chatId: ${{ secrets.TELEGRAM_CI_TO }}
          jobStatus: ${{ job.status }}
          skipSuccess: false
