name: ReleaseCandidate

on:
  push:
    branches: [ rc ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Version
        uses: pCYSl5EDgo/cat@master
        id: version
        with:
          path: VERSION

      - name: Get short SHA
        id: slug
        run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"

      - name: Build & Pus h to Docker Hub
        uses: opspresso/action-docker@master
        env:
          USERNAME: ${{ secrets.DOCKER_HUB_USER }}
          PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
          IMAGE_NAME: "minterteam/explorer-extender-rc"
          DOCKERFILE: ".docker/Dockerfile"
          LATEST: "true"
          VERSION: "${{ steps.version.outputs.text }}"
          TAG_NAME: ${{ github.sha }}
          DOCKER_BUILD_ARGS: --build-arg VERSION=${{ steps.version.outputs.text }}-${{ steps.slug.outputs.sha8 }}-rc

      - name: deploy to production cluster
        uses: wahyd4/kubectl-helm-action@v0.1.2
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_PROD_CONFIG_DATA }}
          TAG_NAME: ${{ github.sha }}
        with:
          args: helm upgrade -n rc -i extender chart/ --atomic --timeout 100s --reuse-values --set image.tag=$TAG_NAME

      - name: notification
        if: cancelled() == false
        uses: xinthink/action-telegram@v1.1
        with:
          botToken: ${{ secrets.TELEGRAM_CI_TOKEN }}
          chatId: ${{ secrets.TELEGRAM_CI_PROD_TO }}
          jobStatus: ${{ job.status }}
          skipSuccess: false
